// <auto-generated />
namespace ASP.Net_MVC_Fundamentals.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateMembershipRecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateMembershipRecords));
        
        string IMigrationMetadata.Id
        {
            get { return "202212201227033_updateMembershipRecords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
